title: Serfies' Tech Insights
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  My blog on IT, Coding, AI, and Architecture topics.

url: "https://serfies.github.io"

# Author settings (used by Minima for the footer)
author:
  name: Serfies
  twitter: your_twitter_handle # Optional: Your Twitter handle (without @)
  github: Serfies # Your GitHub username

#minima:
#  skin: dark
#  date_format: "%b %-d, %Y"
#  nav_pages:
#    - about.md
#  show_excerpts: true  
#  social_links:
#    twitter: your_twitter_handle
#    github: Serfies
#  hide_site_feed_link: true
  
# Theme settings
# _config.yml
#theme: minima

remote_theme: "mmistakes/minimal-mistakes@4.27.1"

# Optional: enable syntax highlighting
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-include-cache


