title: Serfies' Blog
description: My blog on IT, Coding, AI, and Architecture topics.

# Theme settings
# _config.yml
theme: minima

# Optional: enable syntax highlighting
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
